### ISSUE TITLE
Not updating from 2.0.3.3 to 2.0.3.4 after download or restart

### ISSUE THREAD

**Issue by MNoya** [stephenfournier/Dota-2-ModKit#48]
It will keep asking for the version after downloading

**Comment by stephenfournier** [comment]
yes, working on this currently. i made this note on the readme:

Note: D2ModKit may have trouble updating on Windows 10 due to permission issues. After updating there may be both a D2ModKit_new.exe and D2ModKit.exe. Delete D2ModKit.exe and rename D2ModKit_new.exe to D2ModKit.exe.

**Comment by MNoya** [comment]
I'm not on Win 10 though

**Comment by stephenfournier** [comment]
I think it's fixed [with this line](https://github.com/stephenfournier/Dota-2-ModKit/commit/64ffbf7a516a1540e51c09aaee4d4a793d460c51#diff-709ec5d90c6198db99a05373954662e0R113)

but you won't notice a difference until you're at v2.0.3.5.

**Comment by stephenfournier** [comment]
what do u mean by 'unterminated child blocks'?
