### ISSUE TITLE
CM Spelllibrary Bug

### ISSUE THREAD

**Issue by Lemon30** [stephenfournier/Dota-2-ModKit#50]
Hey yo!

In the spell library window, crystal maiden's freezing field's lua button is greyed out. Thus, it's not accessible. 
This one:
https://github.com/Pizzalol/SpellLibrary/blob/master/game/scripts/vscripts/heroes/hero_crystalmaiden/freezing_field.lua

**Comment by Pizzalol** [comment]
This has been fixed with the most recent Spell Library update

**Comment by stephenfournier** [comment]
Thanks @Pizzalol!
